const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Cryptography,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{Dashing: 0},
	{Key: 0},
	{Attack: 0},
	{Carrying_Something: 0},
	{"8Direction": 0},
	{Bullet: 0},
	{ScrollTo: 0},
	{Flash: 0},
	{Player: 0},
	{Solid: 0},
	{MoveTo: 0},
	{Estaniel: 0},
	{Lix: 0},
	{Luci: 0},
	{IsActive: 0},
	{MerchantType: 0},
	{ArmorDemon: 0},
	{DashDMGdemon: 0},
	{HealthDemon: 0},
	{SpeedDemon: 0},
	{StrengthDemon: 0},
	{Pluto: 0},
	{slash: 0},
	{Available: 0},
	{Armor_Hitbox: 0},
	{Das_Hitbox: 0},
	{Health_Hitbox: 0},
	{Lix_Hitbox: 0},
	{Speed_Hitbox: 0},
	{Strenght_Hitbox: 0},
	{Pluto_Hitbox: 0},
	{GoTo: 0},
	{AnotherTriggerObject: 0},
	{doorCollisionToggle: 0},
	{DungeonEntrance_1: 0},
	{Locked: 0},
	{DungeonEntrance_2: 0},
	{Exit_dungeon1: 0},
	{gatecollisionToggle: 0},
	{ObjectRespawn: 0},
	{ID: 0},
	{PlayerSpawn: 0},
	{WallKey: 0},
	{WallOffering: 0},
	{doorcollision_notoggle: 0},
	{Estaniel_DungeonunlockPosition: 0},
	{Destructibles: 0},
	{EnemyHealth: 0},
	{EnemyDrops: 0},
	{Pathfinding: 0},
	{LineOfSight: 0},
	{Enemy: 0},
	{Wotah: 0},
	{PrevX: 0},
	{PrevY: 0},
	{Sine: 0},
	{MovingObject: 0},
	{Offering: 0},
	{Offered: 0},
	{SacrificingCircle: 0},
	{spraying: 0},
	{Spraying_wotah: 0},
	{EnemyDrop: 0},
	{BossHealth: 0},
	{BossState: 0},
	{Sine2: 0},
	{BigBossu: 0},
	{Door2: 0},
	{Door3: 0},
	{Gate: 0},
	{Pipe_LR: 0},
	{Pipe_UD: 0},
	{acquiredd: 0},
	{FancWinebottle: 0},
	{acquired: 0},
	{WineBottle: 0},
	{BookCase1: 0},
	{BookCase2: 0},
	{BookCase_Side: 0},
	{Door_Opentransp: 0},
	{Door3_Opentransp: 0},
	{TiledWater: 0},
	{TiledWaterEnd1: 0},
	{Water0104: 0},
	{Wotah0203: 0},
	{dungeon0203_water: 0},
	{Anchor: 0},
	{UI_Key: 0},
	{Tilemap_: 0},
	{Bar_tilemap: 0},
	{BarFloor: 0},
	{BarFloorTilemap: 0},
	{dungeon_0101: 0},
	{dungeon0101_Ground: 0},
	{dungeon_0102: 0},
	{dungeon_0102_Ground: 0},
	{duingeon0104_Ground: 0},
	{dungeon0103: 0},
	{dungeon0103_Ground: 0},
	{dungeon0104: 0},
	{dungeon0105: 0},
	{dungeon0201_Ground: 0},
	{dungeon0202: 0},
	{dungeon0202_Ground: 0},
	{dungeon0203: 0},
	{dungeon0203_Ground: 0},
	{dungeon0204: 0},
	{dungeon0204_Ground: 0},
	{dungeon10105_Ground: 0},
	{dungeon_0201: 0},
	{Bar_tilemap_Front: 0},
	{dungeon0101_collision: 0},
	{dungeon0101_front: 0},
	{dungeon0102_front: 0},
	{dungeon0103_front: 0},
	{dungeon0104_front: 0},
	{dungeon0105_front: 0},
	{dungeon0201_front: 0},
	{dungeon0202_front: 0},
	{dungeon0203_front: 0},
	{dungeon0204_front: 0},
	{bar_Collision: 0},
	{dungeon0102_collision: 0},
	{dungeon0103_collision: 0},
	{dungeon0104_collision: 0},
	{dungeon0105_collision: 0},
	{dungeon0201_collision: 0},
	{dungeon0202_collision: 0},
	{dungeon0203_collision: 0},
	{dungeon0204_collision: 0},
	{dungeon0105_DoorOverlap: 0},
	{dungeon0201_Overlap: 0},
	{dungeon0202_Overlap: 0},
	{dungeon0203_Overlap: 0},
	{dungeon0204_Overlap: 0},
	{dungeon0104_waterF1: 0},
	{dungeon0104_waterF2: 0},
	{dungeon0104_waterF3: 0},
	{dungeon0104_waterF4: 0},
	{BarTablePiece1: 0},
	{BackshelfL: 0},
	{BackshelfR: 0},
	{Occupied: 0},
	{BarStool: 0},
	{BarTablePiece2: 0},
	{BarTablePiece3: 0},
	{BoaPilaAmigo: 0},
	{Carpet_BottomL: 0},
	{Carpet_BottomMid: 0},
	{Carpet_BottomR: 0},
	{Carpet_MidL: 0},
	{Carpet_MidMid: 0},
	{Carpet_MidR: 0},
	{Carpet_UpMid: 0},
	{Carpet_UpRight: 0},
	{CarpetCorner_UpL: 0},
	{ChairDown: 0},
	{ChairLeft: 0},
	{ChairRight: 0},
	{ChairUp: 0},
	{LixBed: 0},
	{Door1: 0},
	{GuestTable: 0},
	{LuciBed: 0},
	{Trapdoor: 0},
	{BoaPilaAmigo_Halved: 0},
	{BarTablePiece1_Top: 0},
	{BarTablePiece2_Top: 0},
	{BarTablePiece3_Top: 0},
	{Health: 0},
	{MovementUpgrades: 0},
	{StrengthUpgrade: 0},
	{DmgBoost: 0},
	{HeartsEmpty: 0},
	{HeartsFull: 0},
	{Heart_ID: 0},
	{HP: 0},
	{SprintDash: 0},
	{HealthArmored: 0},
	{MoneyCounter: 0},
	{SpaceToPickup: 0},
	{MoneyCount: 0},
	{Bosshealth: 0},
	{Bullet_Boss: 0},
	{Tween: 0},
	{NPCDialogueBG: 0},
	{NpcName: 0},
	{DialogueTxt: 0},
	{BuyTxt: 0},
	{DialChoicesBG: 0},
	{DontBuyTxt: 0},
	{DontBuyDialog: 0},
	{BuyDialog: 0},
	{CreditText: 0},
	{PauseQuit: 0},
	{PauseResume: 0},
	{PressE: 0},
	{PressE2: 0},
	{ReturnStart: 0},
	{credits: 0},
	{GameTitle: 0},
	{play: 0},
	{Quit: 0},
	{Talk: 0},
	{PauseBG: 0},
	{AttackHitbox_provisorischuntilwegottheanimationsthenigottaredothat: 0},
	{checker: 0},
	{debug: 0},
	{exit_checker: 0},
	{Dungeon2Done_Checker: 0},
	{Cryptography: 0},
	{Audio: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Pin: 0},
	{Light: 0},
	{titleImage: 0},
	{Candle: 0},
	{candleLight: 0},
	{CandleLightNew: 0},
	{direction: 0},
	{WithinReach: 0},
	{currentCheckpoint: 0},
	{PlayerHealth: 0},
	{MerchantRoll: 0},
	{Dungeon1Done: 0},
	{Dungeon2Done: 0},
	{CurrentPrice: 0},
	{ChoiceBuyTxt: 0},
	{ChoiceLeaveTxt: 0},
	{InShopChoice: 0},
	{DashDealsDmg: 0},
	{PlayerSpeedBonus: 0},
	{CurrentBuff: 0},
	{Intro1Played: 0},
	{Intro2Played: 0},
	{Intro3Played: 0},
	{DialogueToken: 0},
	{Pause: 0},
	{ArmorHealth: 0},
	{HasArmor: 0},
	{HealthBuffActive: 0},
	{DashHitUsed: 0},
	{CurrentDungeon: 0},
	{PlayerDamage: 0},
	{HasDashDmgBuff: 0},
	{HasHealthBuff: 0},
	{HasStrengthBuff: 0},
	{HasSpeedBuff: 0},
	{HasArmorBuff: 0},
	{normal: 0},
	{enhanced: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Estaniel: class extends self.ISpriteInstance {},
	Lix: class extends self.ISpriteInstance {},
	Luci: class extends self.ISpriteInstance {},
	ArmorDemon: class extends self.ISpriteInstance {},
	DashDMGdemon: class extends self.ISpriteInstance {},
	HealthDemon: class extends self.ISpriteInstance {},
	SpeedDemon: class extends self.ISpriteInstance {},
	StrengthDemon: class extends self.ISpriteInstance {},
	Pluto: class extends self.ISpriteInstance {},
	slash: class extends self.ISpriteInstance {},
	Armor_Hitbox: class extends self.ISpriteInstance {},
	Das_Hitbox: class extends self.ISpriteInstance {},
	Health_Hitbox: class extends self.ISpriteInstance {},
	Lix_Hitbox: class extends self.ISpriteInstance {},
	Speed_Hitbox: class extends self.ISpriteInstance {},
	Strenght_Hitbox: class extends self.ISpriteInstance {},
	Pluto_Hitbox: class extends self.ISpriteInstance {},
	AnotherTriggerObject: class extends self.ISpriteInstance {},
	doorCollisionToggle: class extends self.ISpriteInstance {},
	DungeonEntrance_1: class extends self.ISpriteInstance {},
	DungeonEntrance_2: class extends self.ISpriteInstance {},
	Exit_dungeon1: class extends self.ISpriteInstance {},
	gatecollisionToggle: class extends self.ISpriteInstance {},
	ObjectRespawn: class extends self.ISpriteInstance {},
	PlayerSpawn: class extends self.ISpriteInstance {},
	WallKey: class extends self.ISpriteInstance {},
	WallOffering: class extends self.ISpriteInstance {},
	doorcollision_notoggle: class extends self.ISpriteInstance {},
	Estaniel_DungeonunlockPosition: class extends self.ISpriteInstance {},
	Destructibles: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Wotah: class extends self.ISpriteInstance {},
	MovingObject: class extends self.ISpriteInstance {},
	Key: class extends self.ISpriteInstance {},
	Offering: class extends self.ISpriteInstance {},
	SacrificingCircle: class extends self.ISpriteInstance {},
	Spraying_wotah: class extends self.ISpriteInstance {},
	EnemyDrop: class extends self.ISpriteInstance {},
	BigBossu: class extends self.ISpriteInstance {},
	Door2: class extends self.ISpriteInstance {},
	Door3: class extends self.ISpriteInstance {},
	Gate: class extends self.ISpriteInstance {},
	Pipe_LR: class extends self.ISpriteInstance {},
	Pipe_UD: class extends self.ISpriteInstance {},
	FancWinebottle: class extends self.ISpriteInstance {},
	WineBottle: class extends self.ISpriteInstance {},
	BookCase1: class extends self.ISpriteInstance {},
	BookCase2: class extends self.ISpriteInstance {},
	BookCase_Side: class extends self.ISpriteInstance {},
	Door_Opentransp: class extends self.ISpriteInstance {},
	Door3_Opentransp: class extends self.ISpriteInstance {},
	TiledWater: class extends self.ITiledBackgroundInstance {},
	TiledWaterEnd1: class extends self.ITiledBackgroundInstance {},
	Water0104: class extends self.ISpriteInstance {},
	Wotah0203: class extends self.ISpriteInstance {},
	dungeon0203_water: class extends self.ITilemapInstance {},
	UI_Key: class extends self.ISpriteInstance {},
	Tilemap_: class extends self.ISpriteInstance {},
	Bar_tilemap: class extends self.ITilemapInstance {},
	BarFloor: class extends self.ITiledBackgroundInstance {},
	BarFloorTilemap: class extends self.ITilemapInstance {},
	dungeon_0101: class extends self.ITilemapInstance {},
	dungeon0101_Ground: class extends self.ITilemapInstance {},
	dungeon_0102: class extends self.ITilemapInstance {},
	dungeon_0102_Ground: class extends self.ITilemapInstance {},
	duingeon0104_Ground: class extends self.ITilemapInstance {},
	dungeon0103: class extends self.ITilemapInstance {},
	dungeon0103_Ground: class extends self.ITilemapInstance {},
	dungeon0104: class extends self.ITilemapInstance {},
	dungeon0105: class extends self.ITilemapInstance {},
	dungeon0201_Ground: class extends self.ITilemapInstance {},
	dungeon0202: class extends self.ITilemapInstance {},
	dungeon0202_Ground: class extends self.ITilemapInstance {},
	dungeon0203: class extends self.ITilemapInstance {},
	dungeon0203_Ground: class extends self.ITilemapInstance {},
	dungeon0204: class extends self.ITilemapInstance {},
	dungeon0204_Ground: class extends self.ITilemapInstance {},
	dungeon10105_Ground: class extends self.ITilemapInstance {},
	dungeon_0201: class extends self.ITilemapInstance {},
	Bar_tilemap_Front: class extends self.ITilemapInstance {},
	dungeon0101_collision: class extends self.ITilemapInstance {},
	dungeon0101_front: class extends self.ITilemapInstance {},
	dungeon0102_front: class extends self.ITilemapInstance {},
	dungeon0103_front: class extends self.ITilemapInstance {},
	dungeon0104_front: class extends self.ITilemapInstance {},
	dungeon0105_front: class extends self.ITilemapInstance {},
	dungeon0201_front: class extends self.ITilemapInstance {},
	dungeon0202_front: class extends self.ITilemapInstance {},
	dungeon0203_front: class extends self.ITilemapInstance {},
	dungeon0204_front: class extends self.ITilemapInstance {},
	bar_Collision: class extends self.ITilemapInstance {},
	dungeon0102_collision: class extends self.ITilemapInstance {},
	dungeon0103_collision: class extends self.ITilemapInstance {},
	dungeon0104_collision: class extends self.ITilemapInstance {},
	dungeon0105_collision: class extends self.ITilemapInstance {},
	dungeon0201_collision: class extends self.ITilemapInstance {},
	dungeon0202_collision: class extends self.ITilemapInstance {},
	dungeon0203_collision: class extends self.ITilemapInstance {},
	dungeon0204_collision: class extends self.ITilemapInstance {},
	dungeon0105_DoorOverlap: class extends self.ITilemapInstance {},
	dungeon0201_Overlap: class extends self.ITilemapInstance {},
	dungeon0202_Overlap: class extends self.ITilemapInstance {},
	dungeon0203_Overlap: class extends self.ITilemapInstance {},
	dungeon0204_Overlap: class extends self.ITilemapInstance {},
	dungeon0104_waterF1: class extends self.ITilemapInstance {},
	dungeon0104_waterF2: class extends self.ITilemapInstance {},
	dungeon0104_waterF3: class extends self.ITilemapInstance {},
	dungeon0104_waterF4: class extends self.ITilemapInstance {},
	BarTablePiece1: class extends self.ISpriteInstance {},
	BackshelfL: class extends self.ISpriteInstance {},
	BackshelfR: class extends self.ISpriteInstance {},
	BarStool: class extends self.ISpriteInstance {},
	BarTablePiece2: class extends self.ISpriteInstance {},
	BarTablePiece3: class extends self.ISpriteInstance {},
	BoaPilaAmigo: class extends self.ISpriteInstance {},
	Carpet_BottomL: class extends self.ISpriteInstance {},
	Carpet_BottomMid: class extends self.ISpriteInstance {},
	Carpet_BottomR: class extends self.ISpriteInstance {},
	Carpet_MidL: class extends self.ISpriteInstance {},
	Carpet_MidMid: class extends self.ISpriteInstance {},
	Carpet_MidR: class extends self.ISpriteInstance {},
	Carpet_UpMid: class extends self.ISpriteInstance {},
	Carpet_UpRight: class extends self.ISpriteInstance {},
	CarpetCorner_UpL: class extends self.ISpriteInstance {},
	ChairDown: class extends self.ISpriteInstance {},
	ChairLeft: class extends self.ISpriteInstance {},
	ChairRight: class extends self.ISpriteInstance {},
	ChairUp: class extends self.ISpriteInstance {},
	LixBed: class extends self.ISpriteInstance {},
	Door1: class extends self.ISpriteInstance {},
	GuestTable: class extends self.ISpriteInstance {},
	LuciBed: class extends self.ISpriteInstance {},
	Trapdoor: class extends self.ISpriteInstance {},
	BoaPilaAmigo_Halved: class extends self.ISpriteInstance {},
	BarTablePiece1_Top: class extends self.ISpriteInstance {},
	BarTablePiece2_Top: class extends self.ISpriteInstance {},
	BarTablePiece3_Top: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	MovementUpgrades: class extends self.ISpriteInstance {},
	StrengthUpgrade: class extends self.ISpriteInstance {},
	DmgBoost: class extends self.ISpriteInstance {},
	HeartsEmpty: class extends self.ITiledBackgroundInstance {},
	HeartsFull: class extends self.ITiledBackgroundInstance {},
	HP: class extends self.ISpriteInstance {},
	SprintDash: class extends self.ISpriteInstance {},
	HealthArmored: class extends self.ITiledBackgroundInstance {},
	MoneyCounter: class extends self.ITextInstance {},
	SpaceToPickup: class extends self.ITextInstance {},
	MoneyCount: class extends self.ISpriteInstance {},
	Bosshealth: class extends self.ISpriteInstance {},
	Bullet_Boss: class extends self.ISpriteInstance {},
	NPCDialogueBG: class extends self.ISpriteInstance {},
	NpcName: class extends self.ITextInstance {},
	DialogueTxt: class extends self.ITextInstance {},
	BuyTxt: class extends self.ITextInstance {},
	DialChoicesBG: class extends self.ISpriteInstance {},
	DontBuyTxt: class extends self.ITextInstance {},
	DontBuyDialog: class extends self.ITextInstance {},
	BuyDialog: class extends self.ITextInstance {},
	CreditText: class extends self.ITextInstance {},
	PauseQuit: class extends self.ITextInstance {},
	PauseResume: class extends self.ITextInstance {},
	PressE: class extends self.ITextInstance {},
	PressE2: class extends self.ITextInstance {},
	ReturnStart: class extends self.ITextInstance {},
	credits: class extends self.ITextInstance {},
	GameTitle: class extends self.ITextInstance {},
	play: class extends self.ITextInstance {},
	Quit: class extends self.ITextInstance {},
	Talk: class extends self.ITextInstance {},
	PauseBG: class extends self.ITiledBackgroundInstance {},
	AttackHitbox_provisorischuntilwegottheanimationsthenigottaredothat: class extends self.ISpriteInstance {},
	checker: class extends self.ITextInstance {},
	debug: class extends self.ITextInstance {},
	exit_checker: class extends self.ITextInstance {},
	Dungeon2Done_Checker: class extends self.ISpriteInstance {},
	Cryptography: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Light: class extends self.ISpriteInstance {},
	titleImage: class extends self.ISpriteInstance {},
	Candle: class extends self.ISpriteInstance {},
	candleLight: class extends self.ISpriteInstance {},
	CandleLightNew: class extends self.ISpriteInstance {}
}