const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.shadowcaster,
		C3.Plugins.shadowlight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.shadowlight.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Mouse.Exps.AbsoluteX,
		C3.Plugins.Mouse.Exps.AbsoluteY
	];
};
self.C3_JsPropNameTable = [
	{mazebase: 0},
	{freeSpace: 0},
	{"8Richtungen": 0},
	{ScrolleZu: 0},
	{Player: 0},
	{LineOfSight: 0},
	{Wegfindung: 0},
	{MoveTo: 0},
	{pappanorizzo: 0},
	{Text: 0},
	{Goal: 0},
	{gameoverText: 0},
	{PlayButton: 0},
	{Mouse: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Bg: 0},
	{Map: 0},
	{Path: 0},
	{KeyboardForAnimation: 0},
	{Mazefloor: 0},
	{DrawingCanvas: 0},
	{MazeWalls: 0},
	{ShadowCaster: 0},
	{Walls_Tilemap_PLS: 0},
	{yeet: 0},
	{Walls_Tilemap_PLS2: 0},
	{WinScreenChenjawis: 0},
	{LoseScreenChenchu: 0},
	{Sprite: 0}
];

self.InstanceType = {
	mazebase: class extends self.ISpriteInstance {},
	freeSpace: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	pappanorizzo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Goal: class extends self.ISpriteInstance {},
	gameoverText: class extends self.ITextInstance {},
	PlayButton: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	Map: class extends self.ITilemapInstance {},
	Path: class extends self.ITilemapInstance {},
	KeyboardForAnimation: class extends self.IInstance {},
	Mazefloor: class extends self.ISpriteInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	MazeWalls: class extends self.ISpriteInstance {},
	Walls_Tilemap_PLS: class extends self.ITilemapInstance {},
	yeet: class extends self.IShadowLightInstance {},
	Walls_Tilemap_PLS2: class extends self.ITilemapInstance {},
	WinScreenChenjawis: class extends self.ISpriteInstance {},
	LoseScreenChenchu: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {}
}